# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Renacer Yoga

email: jav.brustolon@gmail.com

description: >- # this means to ignore newlines until "baseurl:"
  Bienvenido a renacer yoga. Somos un centro dedicado al estudio del yoga y de la medicina ayurveda

jumbotron-description: Bienvenido a renacer yoga. Somos un centro dedicado al estudio del yoga y de la medicina ayurveda

baseurl: "/base-template" # the subpath of your site, e.g. /blog

url: "https://javfr.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

#Social
twitter_username: 
github_username:  JavFr

#Languages
lang: es-AR

# Build settings
theme: minima

#Material Design Bootstrap 
mdb: true

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/


#CONFIGURATION

#Lets to publish future posts dates
future: true

#Collections
collections:
  events:
    output: true
  
  lessons:
    output: true

defaults:
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
  - scope:
      path: ""
      type: "lessons"
    values:
      layout: "lesson"
  - scope:
      path: ""
    values:
      layout: "default"